name: CI tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with test
    - name: Run tests
      env:
        IMQCAM_API_KEY: ${{ secrets.IMQCAM_API_KEY }}
      run: poetry run pytest
    - name: Generate coverage badge
      run: coverage-badge -o coverage.svg
    - name: Upload coverage badge
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: coverage.svg
