name: CI tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with test
    - name: Run tests
      env:
        IMQCAM_API_KEY: ${{ secrets.IMQCAM_API_KEY }}
      run: poetry run pytest
    - name: Generate coverage badge
      run: |
        poetry run coverage-badge -o coverage_badge.svg
        git config --global user.email "margaret.eminizer@gmail.com"
        git config --global user.name "Maggie Eminizer"
        git pull --ff-only origin gh-pages
        git checkout gh-pages
        git add coverage_badge.svg
        git commit -m "Update coverage badge"
        git push origin gh-pages
